#!/usr/bin/env bash
#
# Stephen Patrick Vicchio
# 2020-08-18 
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 
# Travels to the scratch2 directory containing your job
# 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 
#  INPUT: JOBID for the job scratch directory you'd like to visit 
# OUTPUT: Nothing (except you are now in the scratch directory)
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 
# To run properly, you must either:
#	(1) type '. FIND #########' into the command line 
#       (2) add alias FIND='. FIND' to your .bashrc
# 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  


JOBID=${1%.*}

find_status=False
if [[ -n $(find /scratch1/${USER} -maxdepth 1 -name "*${JOBID}.pbs02") && ${find_status} == False ]]; then
	cd $(find /scratch1/${USER} -maxdepth 1 -name "*${JOBID}.pbs02")  
	echo ''
	echo 'Now switching to /scratch1 dir:'
	pwd
	echo ''
	ls
	echo ''
	find_status=True
fi

if [[ ${find_status} == False ]]; then 
       echo ''
       echo 'The directory you are looking for DOES NOT exist.'
       echo ''
fi 


